### ISSUE TITLE
cutcutgo-app.bin generation error

### ISSUE THREAD

**Issue by Rockman18** [virtualabs/cutcutgo#10]
Really strange message when trying to generate bin file on my docker github_action. 

``` shell
Run cd utils && ./cutcutgo_mkuf2.sh
objcopy: ../cutcutgo.X/dist/cutcutgo_bl/production/cutcutgo-app.bin: Bad file descriptor
Traceback (most recent call last):
  File "/home/runner/work/cutcutgo/cutcutgo/utils/./uf2conv.py", line 3[6](https://github.com/Rockman18/cutcutgo/actions/runs/6594098113/job/17917558820#step:6:7)1, in <module>
    main()
  File "/home/runner/work/cutcutgo/cutcutgo/utils/./uf2conv.py", line 31[8](https://github.com/Rockman18/cutcutgo/actions/runs/6594098113/job/17917558820#step:6:9), in main
    with open(args.input, mode='rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '../cutcutgo.X/dist/cutcutgo_bl/production/cutcutgo-app.bin'
Error: Process completed with exit code 1.
```

**Comment by Rockman18** [comment]
False mistake. Write permissions are not set on dist directory on my docker for the mkuf2 script.
